### PR TITLE
Fix small ui issues

### PR DESCRIPTION
**Pull request by jonatan-kruse**
I think easiest for you would be to try the branchs' ui your-self

### CODE REVIEW

**Comment by ErikLundb3rg** [comment]
Looks nice, do you want to look into also fixing the hover effect on the graphs?
The text is a little hard to read and I think the values should be rounded. 

image

**Comment by ErikLundb3rg** [comment]
Also saw that the play box is buggy: 
image

That one is on me but if you want to fix it would be greatly appreciated ^^

**Review by ErikLundb3rg — CHANGES_REQUESTED** [review]
See comments, I think the graph rounding should be changed. Otherwise looking good.

**Comment by jonatan-kruse** [comment]
And yes didn't put any time on scaling the play box on window size but can be done in a future PR

**Comment by jonatan-kruse** [comment]
I hate the librarys tooltip functionality, if you want to look in to changeing the colors or the background color pkeas do, I also want it fixed

**Review by ErikLundb3rg — APPROVED** [review]

**Comment by ErikLundb3rg** [comment]
Cool cool, create issues for tooltip functionality if that bugs you.

**Pull request merged**
